# Common Labels
labels:
  app: "naljal-custom-service"
  group: "rainmaker"

# Ingress Configs
ingress:
  enabled: true
  zuul: true
  context: "naljal-custom-service"

# Init Containers Configs
initContainers: {}

# Container Configs
image:
  repository: "naljal-custom-service"
replicas: "1"
healthChecks:
  enabled: true
  livenessProbePath: "/naljal-custom-service/health"
  readinessProbePath: "/naljal-custom-service/health"
appType: "java-spring"
tracing-enabled: true
heap: "-Xmx192m -Xms192m"
java-args: "-Dspring.profiles.active=monitoring"

# Additional Container Envs
env: |
  {{- if and (.Values.global.context.path) (has .Values.name .Values.global.context.list) }}
  - name: SERVER_CONTEXT_PATH
    value: /{{ .Values.global.context.path }}/{{ .Values.ingress.context }}
  - name: SERVER_SERVLET_CONTEXT_PATH
    value: /{{ .Values.global.context.path }}/{{ .Values.ingress.context }}
  {{- else }}
  - name: SERVER_CONTEXT_PATH
    value: /{{ .Values.ingress.context }}
  - name: SERVER_SERVLET_CONTEXT_PATH
    value: /{{ .Values.ingress.context }}
  {{- end }}
  - name: SPRING_KAFKA_CONSUMER_GROUP_ID
    value: naljal-custom-service
  - name: SPRING_KAFKA_PRODUCER_KEY_SERIALIZER
    value: org.apache.kafka.common.serialization.StringSerializer
  - name: SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER
    value: org.springframework.kafka.support.serializer.JsonSerializer
  - name: EGOV_MDMS_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-mdms-service
  - name: EGOV_MDMS_SEARCH_ENDPOINT
    value: {{ index .Values "egov-mdms-search-endpoint" | quote }}
  - name: EGOV_PROPERTY_SERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: property-services
  - name: EGOV_COLLECTION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: collection-services
  - name: EGOV_BILLINGSERVICE_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: billing-service
  - name: EGOV_LOCALIZATION_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-localization
  - name: EGOV_USER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-user  
  - name: EGOV_URL_SHORTNER_HOST
    valueFrom:
      configMapKeyRef:
        name: egov-service-host
        key: egov-url-shortening     
  - name: EGOV_SHORTENER_URL
    value: {{ index .Values "egov-shortener-url" | quote }}
  - name: EGOV_URL_SHORTNER_ENDPOINT
    value: {{ index .Values "egov-url-shortener-endpoint" | quote }} 
  - name: EGOV_MGRAMSEVA_UI_PATH
    value: mgramseva/login
  - name: JAVA_OPTS
    value: {{ index .Values "heap" | quote }}
  - name: JAVA_ARGS
    value: {{ index .Values "java-args" | quote }}
  - name: EGOV_URL_SHORTNER_ENDPOINT
    value: {{ index .Values "egov-url-shortener-endpoint" | quote }}
  - name: SERVER_PORT
    value: "8080"
  - name: SECURITY_BASIC_ENABLED
    value: "false"  
  - name: MANAGEMENT_SECURITY_ENABLED
    value: "false"
  {{- if index .Values "tracing-enabled" }}
  - name: TRACER_OPENTRACING_ENABLED
    value: "true" 
  {{- end }}
