output "vpc_id" {
  value = var.vpc_id
}


output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}


output "db_instance_endpoint" {
  value = var.db_instance_endpoint
}


output "db_instance_name" {
  description = "The database name"
  value       = var.db_instance_name
}

output "zone" {
  value = var.availability_zones
}

output "worker_security_group_id" {
  description = "The security group id of worker nodes"
  value       = module.eks.worker_security_group_id
}

output "eks_cluster_iam_role_name" {
  value = module.eks.cluster_iam_role_name
}